### ISSUE TITLE
heatmaps

### ISSUE THREAD

**Issue by ghost** [tbwxmu/MolD_pipeline#1]
What are the labels on the x-axis and y-axis???

It's hard to read the heatmaps without knowing what the axes mean.

**Comment by tbwxmu** [comment]
both are the number of used neurons. There are x*y  neurons in the heatmap as you see.

**Comment by ghost** [comment]
Thank you. If some more information could be given that’d be great. I am interested in the classification. Btw, iris.txt mentioned in the notebook is not available.

**Comment by tbwxmu** [comment]
`python mol_SOM.py` get what you want
